/**
 * This array generated by OpenAI - gives an examples to various finite state machines
 */

export const FiniteStateMachinesExamples = [
    {
        name: 'Vending Machine',
        description: 'A simple FSM modeling a vending machine that dispenses snacks or drinks based on user input.'
    },
    {
        name: 'Traffic Light Controller',
        description: 'An FSM controlling the state transitions of a traffic light system, including red, yellow, and green lights.'
    },
    {
        name: 'Elevator Control',
        description: 'A FSM representing the control logic for an elevator, handling floor requests and door operations.'
    },
    {
        name: 'Turnstile',
        description: 'A basic FSM for a turnstile that allows or denies access based on the user\'s input and the current state.'
    },
    {
        name: 'Washer/Dryer',
        description: 'An FSM modeling the operation of a washer/dryer machine, including washing, rinsing, and drying cycles.'
    },
    {
        name: 'Email Inbox',
        description: 'An FSM representing the state transitions of an email inbox, including reading, replying, and archiving emails.'
    },
    {
        name: 'Game Character AI',
        description: 'A FSM controlling the behavior of a game character, with states like idle, attacking, fleeing, and patrolling.'
    },
    {
        name: 'Automated Teller Machine (ATM)',
        description: 'An FSM for an ATM, handling various user interactions like balance inquiry, cash withdrawal, and deposit.'
    },
    {
        name: 'Simple Alarm System',
        description: 'A basic FSM for an alarm system with states for arming, disarming, and triggering the alarm.'
    },
    {
        name: 'Ecosystem Simulation',
        description: 'An FSM simulating the interactions between predators and prey in a virtual ecosystem.'
    }
]